---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

# Data frame de Iris

```{r}
df = iris
head(df, 5) #Muestra los primeros 5 row
tail(df, 5) #Muestra los ultimos 5 row
names(df)   #Nombre de las columnas del data frame "Igual a colname"
rownames(df)#Nombre de las Filas
str(df)     #Muestra datos del Data Frame
dimnames(df)#Devuelve rownames y names
nrow(df)    #Numero de filas  
ncol(df)    #Numero de Columnas
dim(df)     #Numero de filas y columnas

#Todo se devuelve como string

df$Petal.Length[1:10] #Arma un vector con los 10 primeros
df$Species[1:10]
#df[n,m]     #Sub-DataFrame
```

## Acceso al DataFrame
```{r}
df[1:10, ] #trae del 1 al 10 los df con todas las columnas
df[1:10, 2:4] #Filas de la 1 a la 10 y columnas de la 2 a la 4
df[df$Species=="setosa" & df$Sepal.Width>4, ][c(1,3), c(2,5)]
```


```{r}
dataOrange = Orange
dataOrange[2,3]
head(dataOrange, 5)
str(dataOrange)
dataOrange[dataOrange$circumference>50, ]
```
 
```{r}
read.table() #Lee un fichero de texto simple en la pc local o link
```



