---
title: "Ejemplo Final"
author: "Facundo"
date: "22/7/2020"
output: html_document
---
# Ejemplo Final
## Juntar color de ojo y pelo sin distinguir por sexo

```{r}
ftable(HairEyeColor)
male <- HairEyeColor[, ,"Male"] #Me quedo solo con los hombres
female <- HairEyeColor[, ,"Female"] #Me quedo solo con las Mujeres
data <- as.table(male + female)
data
```
## Manipulacion de datos
```{r}
dimnames(data)=list(
  Pelo=c("Negro","Marron","Rojo","Rubio"),
  Ojo=c("Marrones","Azules","Pardos","Verde")
)
data
```

## Diagrama de mosaico
```{r}
plot(data, col = c("lightblue"), main="Diagrama de mosaico")

```
## Datos Numericos

```{r}
sum(data)
```


```{r}
sum(data)
colSums(data) #frecuencia absoluta
rowSums(data)#frecuencia absoluta
prop.table(colSums(data))#frecuencia relativa
prop.table(rowSums(data))#frecuencia relativa
```
## Diagramas de barra
```{r}
barplot(prop.table(colSums(data)),ylim=c(0,0.4),beside = TRUE,names=c("Marron","Azules","Pardos","Verdes"),col =c("brown","lightblue","orange","green") )
barplot(prop.table(rowSums(data)),ylim=c(0,0.6),beside = TRUE,names=c("Negro","Marron","Rojo","Rubio"),col =c("black","brown","red","yellow"))
```

## Fracuencias relativas globales y marginales
```{r}
round(prop.table(data),3)#Fracuencias relativas globales
round(prop.table(data, margin=1),3)#Frecuancia relativa marginal
round(prop.table(data, margin=2),3)
```

```{r}
barplot(prop.table(data, margin=1),ylim=c(0,0.8),beside = TRUE,names=c("Marron","Azules","Pardos","Verdes"),col =c("black","brown","red","yellow"),legend.text = TRUE )

barplot(t(prop.table(data, margin=2)),ylim=c(0,0.7),beside = TRUE,names=c("Negro","Marron","Rojo","Rubio"),col =c("brown","lightblue","orange","green"),legend.text = TRUE,main = "Frecuencia relativa del color de cabello en cada color de ojo" )
```

